// Generated by scripts/generate-parshiot.mjs. Do not edit by hand.
import { ParshaInfo } from '@/types';

export const PARSHIOT: ParshaInfo[] = [
  {
    "name": "Bereshit",
    "hebrewName": "בראשית",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 1,
        "startVerse": 1,
        "endChapter": 2,
        "endVerse": 3,
        "verseCount": 34
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 2,
        "startVerse": 4,
        "endChapter": 2,
        "endVerse": 19,
        "verseCount": 16
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 2,
        "startVerse": 20,
        "endChapter": 3,
        "endVerse": 21,
        "verseCount": 27
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 3,
        "startVerse": 22,
        "endChapter": 4,
        "endVerse": 18,
        "verseCount": 21
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 4,
        "startVerse": 19,
        "endChapter": 4,
        "endVerse": 22,
        "verseCount": 4
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 4,
        "startVerse": 23,
        "endChapter": 5,
        "endVerse": 24,
        "verseCount": 28
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 5,
        "startVerse": 25,
        "endChapter": 6,
        "endVerse": 8,
        "verseCount": 16
      }
    ],
    "totalVerses": 146,
    "parshaNum": 1
  },
  {
    "name": "Noach",
    "hebrewName": "נח",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 6,
        "startVerse": 9,
        "endChapter": 6,
        "endVerse": 22,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 7,
        "startVerse": 1,
        "endChapter": 7,
        "endVerse": 16,
        "verseCount": 16
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 7,
        "startVerse": 17,
        "endChapter": 8,
        "endVerse": 14,
        "verseCount": 22
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 8,
        "startVerse": 15,
        "endChapter": 9,
        "endVerse": 7,
        "verseCount": 15
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 9,
        "startVerse": 8,
        "endChapter": 9,
        "endVerse": 17,
        "verseCount": 10
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 9,
        "startVerse": 18,
        "endChapter": 10,
        "endVerse": 32,
        "verseCount": 44
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 11,
        "startVerse": 1,
        "endChapter": 11,
        "endVerse": 32,
        "verseCount": 32
      }
    ],
    "totalVerses": 153,
    "parshaNum": 2
  },
  {
    "name": "Lech-Lecha",
    "hebrewName": "לך־לך",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 12,
        "startVerse": 1,
        "endChapter": 12,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 12,
        "startVerse": 14,
        "endChapter": 13,
        "endVerse": 4,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 13,
        "startVerse": 5,
        "endChapter": 13,
        "endVerse": 18,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 14,
        "startVerse": 1,
        "endChapter": 14,
        "endVerse": 20,
        "verseCount": 20
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 14,
        "startVerse": 21,
        "endChapter": 15,
        "endVerse": 6,
        "verseCount": 10
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 15,
        "startVerse": 7,
        "endChapter": 17,
        "endVerse": 6,
        "verseCount": 37
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 17,
        "startVerse": 7,
        "endChapter": 17,
        "endVerse": 27,
        "verseCount": 21
      }
    ],
    "totalVerses": 126,
    "parshaNum": 3
  },
  {
    "name": "Vayera",
    "hebrewName": "וירא",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 18,
        "startVerse": 1,
        "endChapter": 18,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 18,
        "startVerse": 15,
        "endChapter": 18,
        "endVerse": 33,
        "verseCount": 19
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 19,
        "startVerse": 1,
        "endChapter": 19,
        "endVerse": 20,
        "verseCount": 20
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 19,
        "startVerse": 21,
        "endChapter": 21,
        "endVerse": 4,
        "verseCount": 40
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 21,
        "startVerse": 5,
        "endChapter": 21,
        "endVerse": 21,
        "verseCount": 17
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 21,
        "startVerse": 22,
        "endChapter": 21,
        "endVerse": 34,
        "verseCount": 13
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 22,
        "startVerse": 1,
        "endChapter": 22,
        "endVerse": 24,
        "verseCount": 24
      }
    ],
    "totalVerses": 147,
    "parshaNum": 4
  },
  {
    "name": "Chayei Sara",
    "hebrewName": "חיי שרה",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 23,
        "startVerse": 1,
        "endChapter": 23,
        "endVerse": 16,
        "verseCount": 16
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 23,
        "startVerse": 17,
        "endChapter": 24,
        "endVerse": 9,
        "verseCount": 13
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 24,
        "startVerse": 10,
        "endChapter": 24,
        "endVerse": 26,
        "verseCount": 17
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 24,
        "startVerse": 27,
        "endChapter": 24,
        "endVerse": 52,
        "verseCount": 26
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 24,
        "startVerse": 53,
        "endChapter": 24,
        "endVerse": 67,
        "verseCount": 15
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 25,
        "startVerse": 1,
        "endChapter": 25,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 25,
        "startVerse": 12,
        "endChapter": 25,
        "endVerse": 18,
        "verseCount": 7
      }
    ],
    "totalVerses": 105,
    "parshaNum": 5
  },
  {
    "name": "Toldot",
    "hebrewName": "תולדות",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 25,
        "startVerse": 19,
        "endChapter": 26,
        "endVerse": 5,
        "verseCount": 21
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 26,
        "startVerse": 6,
        "endChapter": 26,
        "endVerse": 12,
        "verseCount": 7
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 26,
        "startVerse": 13,
        "endChapter": 26,
        "endVerse": 22,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 26,
        "startVerse": 23,
        "endChapter": 26,
        "endVerse": 29,
        "verseCount": 7
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 26,
        "startVerse": 30,
        "endChapter": 27,
        "endVerse": 27,
        "verseCount": 33
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 27,
        "startVerse": 28,
        "endChapter": 28,
        "endVerse": 4,
        "verseCount": 23
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 28,
        "startVerse": 5,
        "endChapter": 28,
        "endVerse": 9,
        "verseCount": 5
      }
    ],
    "totalVerses": 106,
    "parshaNum": 6
  },
  {
    "name": "Vayetzei",
    "hebrewName": "ויצא",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 28,
        "startVerse": 10,
        "endChapter": 28,
        "endVerse": 22,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 29,
        "startVerse": 1,
        "endChapter": 29,
        "endVerse": 17,
        "verseCount": 17
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 29,
        "startVerse": 18,
        "endChapter": 30,
        "endVerse": 13,
        "verseCount": 31
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 30,
        "startVerse": 14,
        "endChapter": 30,
        "endVerse": 27,
        "verseCount": 14
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 30,
        "startVerse": 28,
        "endChapter": 31,
        "endVerse": 16,
        "verseCount": 32
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 31,
        "startVerse": 17,
        "endChapter": 31,
        "endVerse": 42,
        "verseCount": 26
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 31,
        "startVerse": 43,
        "endChapter": 32,
        "endVerse": 3,
        "verseCount": 15
      }
    ],
    "totalVerses": 148,
    "parshaNum": 7
  },
  {
    "name": "Vayishlach",
    "hebrewName": "וישלח",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 32,
        "startVerse": 4,
        "endChapter": 32,
        "endVerse": 13,
        "verseCount": 10
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 32,
        "startVerse": 14,
        "endChapter": 32,
        "endVerse": 30,
        "verseCount": 17
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 32,
        "startVerse": 31,
        "endChapter": 33,
        "endVerse": 5,
        "verseCount": 8
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 33,
        "startVerse": 6,
        "endChapter": 33,
        "endVerse": 20,
        "verseCount": 15
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 34,
        "startVerse": 1,
        "endChapter": 35,
        "endVerse": 11,
        "verseCount": 42
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 35,
        "startVerse": 12,
        "endChapter": 36,
        "endVerse": 19,
        "verseCount": 37
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 36,
        "startVerse": 20,
        "endChapter": 36,
        "endVerse": 43,
        "verseCount": 24
      }
    ],
    "totalVerses": 153,
    "parshaNum": 8
  },
  {
    "name": "Vayeshev",
    "hebrewName": "וישב",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 37,
        "startVerse": 1,
        "endChapter": 37,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 37,
        "startVerse": 12,
        "endChapter": 37,
        "endVerse": 22,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 37,
        "startVerse": 23,
        "endChapter": 37,
        "endVerse": 36,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 38,
        "startVerse": 1,
        "endChapter": 38,
        "endVerse": 30,
        "verseCount": 30
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 39,
        "startVerse": 1,
        "endChapter": 39,
        "endVerse": 6,
        "verseCount": 6
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 39,
        "startVerse": 7,
        "endChapter": 39,
        "endVerse": 23,
        "verseCount": 17
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 40,
        "startVerse": 1,
        "endChapter": 40,
        "endVerse": 23,
        "verseCount": 23
      }
    ],
    "totalVerses": 112,
    "parshaNum": 9
  },
  {
    "name": "Miketz",
    "hebrewName": "מקץ",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 41,
        "startVerse": 1,
        "endChapter": 41,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 41,
        "startVerse": 15,
        "endChapter": 41,
        "endVerse": 38,
        "verseCount": 24
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 41,
        "startVerse": 39,
        "endChapter": 41,
        "endVerse": 52,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 41,
        "startVerse": 53,
        "endChapter": 42,
        "endVerse": 18,
        "verseCount": 23
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 42,
        "startVerse": 19,
        "endChapter": 43,
        "endVerse": 15,
        "verseCount": 35
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 43,
        "startVerse": 16,
        "endChapter": 43,
        "endVerse": 29,
        "verseCount": 14
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 43,
        "startVerse": 30,
        "endChapter": 44,
        "endVerse": 17,
        "verseCount": 22
      }
    ],
    "totalVerses": 146,
    "parshaNum": 10
  },
  {
    "name": "Vayigash",
    "hebrewName": "ויגש",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 44,
        "startVerse": 18,
        "endChapter": 44,
        "endVerse": 30,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 44,
        "startVerse": 31,
        "endChapter": 45,
        "endVerse": 7,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 45,
        "startVerse": 8,
        "endChapter": 45,
        "endVerse": 18,
        "verseCount": 11
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 45,
        "startVerse": 19,
        "endChapter": 45,
        "endVerse": 27,
        "verseCount": 9
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 45,
        "startVerse": 28,
        "endChapter": 46,
        "endVerse": 27,
        "verseCount": 28
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 46,
        "startVerse": 28,
        "endChapter": 47,
        "endVerse": 10,
        "verseCount": 17
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 47,
        "startVerse": 11,
        "endChapter": 47,
        "endVerse": 27,
        "verseCount": 17
      }
    ],
    "totalVerses": 106,
    "parshaNum": 11
  },
  {
    "name": "Vayechi",
    "hebrewName": "ויחי",
    "book": "Genesis",
    "aliyot": [
      {
        "number": 1,
        "book": "Genesis",
        "startChapter": 47,
        "startVerse": 28,
        "endChapter": 48,
        "endVerse": 9,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Genesis",
        "startChapter": 48,
        "startVerse": 10,
        "endChapter": 48,
        "endVerse": 16,
        "verseCount": 7
      },
      {
        "number": 3,
        "book": "Genesis",
        "startChapter": 48,
        "startVerse": 17,
        "endChapter": 48,
        "endVerse": 22,
        "verseCount": 6
      },
      {
        "number": 4,
        "book": "Genesis",
        "startChapter": 49,
        "startVerse": 1,
        "endChapter": 49,
        "endVerse": 18,
        "verseCount": 18
      },
      {
        "number": 5,
        "book": "Genesis",
        "startChapter": 49,
        "startVerse": 19,
        "endChapter": 49,
        "endVerse": 26,
        "verseCount": 8
      },
      {
        "number": 6,
        "book": "Genesis",
        "startChapter": 49,
        "startVerse": 27,
        "endChapter": 50,
        "endVerse": 20,
        "verseCount": 27
      },
      {
        "number": 7,
        "book": "Genesis",
        "startChapter": 50,
        "startVerse": 21,
        "endChapter": 50,
        "endVerse": 26,
        "verseCount": 6
      }
    ],
    "totalVerses": 85,
    "parshaNum": 12
  },
  {
    "name": "Shemot",
    "hebrewName": "שמות",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 1,
        "startVerse": 1,
        "endChapter": 1,
        "endVerse": 17,
        "verseCount": 17
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 1,
        "startVerse": 18,
        "endChapter": 2,
        "endVerse": 10,
        "verseCount": 15
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 2,
        "startVerse": 11,
        "endChapter": 2,
        "endVerse": 25,
        "verseCount": 15
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 3,
        "startVerse": 1,
        "endChapter": 3,
        "endVerse": 15,
        "verseCount": 15
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 3,
        "startVerse": 16,
        "endChapter": 4,
        "endVerse": 17,
        "verseCount": 24
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 4,
        "startVerse": 18,
        "endChapter": 4,
        "endVerse": 31,
        "verseCount": 14
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 5,
        "startVerse": 1,
        "endChapter": 6,
        "endVerse": 1,
        "verseCount": 24
      }
    ],
    "totalVerses": 124,
    "parshaNum": 13
  },
  {
    "name": "Vaera",
    "hebrewName": "וארא",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 6,
        "startVerse": 2,
        "endChapter": 6,
        "endVerse": 13,
        "verseCount": 12
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 6,
        "startVerse": 14,
        "endChapter": 6,
        "endVerse": 28,
        "verseCount": 15
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 6,
        "startVerse": 29,
        "endChapter": 7,
        "endVerse": 7,
        "verseCount": 9
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 7,
        "startVerse": 8,
        "endChapter": 8,
        "endVerse": 6,
        "verseCount": 28
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 8,
        "startVerse": 7,
        "endChapter": 8,
        "endVerse": 18,
        "verseCount": 12
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 8,
        "startVerse": 19,
        "endChapter": 9,
        "endVerse": 16,
        "verseCount": 26
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 9,
        "startVerse": 17,
        "endChapter": 9,
        "endVerse": 35,
        "verseCount": 19
      }
    ],
    "totalVerses": 121,
    "parshaNum": 14
  },
  {
    "name": "Bo",
    "hebrewName": "בא",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 10,
        "startVerse": 1,
        "endChapter": 10,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 10,
        "startVerse": 12,
        "endChapter": 10,
        "endVerse": 23,
        "verseCount": 12
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 10,
        "startVerse": 24,
        "endChapter": 11,
        "endVerse": 3,
        "verseCount": 9
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 11,
        "startVerse": 4,
        "endChapter": 12,
        "endVerse": 20,
        "verseCount": 27
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 12,
        "startVerse": 21,
        "endChapter": 12,
        "endVerse": 28,
        "verseCount": 8
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 12,
        "startVerse": 29,
        "endChapter": 12,
        "endVerse": 51,
        "verseCount": 23
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 13,
        "startVerse": 1,
        "endChapter": 13,
        "endVerse": 16,
        "verseCount": 16
      }
    ],
    "totalVerses": 106,
    "parshaNum": 15
  },
  {
    "name": "Beshalach",
    "hebrewName": "בשלח",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 13,
        "startVerse": 17,
        "endChapter": 14,
        "endVerse": 8,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 14,
        "startVerse": 9,
        "endChapter": 14,
        "endVerse": 14,
        "verseCount": 6
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 14,
        "startVerse": 15,
        "endChapter": 14,
        "endVerse": 25,
        "verseCount": 11
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 14,
        "startVerse": 26,
        "endChapter": 15,
        "endVerse": 26,
        "verseCount": 32
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 15,
        "startVerse": 27,
        "endChapter": 16,
        "endVerse": 10,
        "verseCount": 11
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 16,
        "startVerse": 11,
        "endChapter": 16,
        "endVerse": 36,
        "verseCount": 26
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 17,
        "startVerse": 1,
        "endChapter": 17,
        "endVerse": 16,
        "verseCount": 16
      }
    ],
    "totalVerses": 116,
    "parshaNum": 16
  },
  {
    "name": "Yitro",
    "hebrewName": "יתרו",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 18,
        "startVerse": 1,
        "endChapter": 18,
        "endVerse": 12,
        "verseCount": 12
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 18,
        "startVerse": 13,
        "endChapter": 18,
        "endVerse": 23,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 18,
        "startVerse": 24,
        "endChapter": 18,
        "endVerse": 27,
        "verseCount": 4
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 19,
        "startVerse": 1,
        "endChapter": 19,
        "endVerse": 6,
        "verseCount": 6
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 19,
        "startVerse": 7,
        "endChapter": 19,
        "endVerse": 19,
        "verseCount": 13
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 19,
        "startVerse": 20,
        "endChapter": 20,
        "endVerse": 14,
        "verseCount": 20
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 20,
        "startVerse": 15,
        "endChapter": 20,
        "endVerse": 23,
        "verseCount": 9
      }
    ],
    "totalVerses": 75,
    "parshaNum": 17
  },
  {
    "name": "Mishpatim",
    "hebrewName": "משפטים",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 21,
        "startVerse": 1,
        "endChapter": 21,
        "endVerse": 19,
        "verseCount": 19
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 21,
        "startVerse": 20,
        "endChapter": 22,
        "endVerse": 3,
        "verseCount": 21
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 22,
        "startVerse": 4,
        "endChapter": 22,
        "endVerse": 26,
        "verseCount": 23
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 22,
        "startVerse": 27,
        "endChapter": 23,
        "endVerse": 5,
        "verseCount": 9
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 23,
        "startVerse": 6,
        "endChapter": 23,
        "endVerse": 19,
        "verseCount": 14
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 23,
        "startVerse": 20,
        "endChapter": 23,
        "endVerse": 25,
        "verseCount": 6
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 23,
        "startVerse": 26,
        "endChapter": 24,
        "endVerse": 18,
        "verseCount": 26
      }
    ],
    "totalVerses": 118,
    "parshaNum": 18
  },
  {
    "name": "Terumah",
    "hebrewName": "תרומה",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 25,
        "startVerse": 1,
        "endChapter": 25,
        "endVerse": 16,
        "verseCount": 16
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 25,
        "startVerse": 17,
        "endChapter": 25,
        "endVerse": 40,
        "verseCount": 24
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 26,
        "startVerse": 1,
        "endChapter": 26,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 26,
        "startVerse": 15,
        "endChapter": 26,
        "endVerse": 30,
        "verseCount": 16
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 26,
        "startVerse": 31,
        "endChapter": 26,
        "endVerse": 37,
        "verseCount": 7
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 27,
        "startVerse": 1,
        "endChapter": 27,
        "endVerse": 8,
        "verseCount": 8
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 27,
        "startVerse": 9,
        "endChapter": 27,
        "endVerse": 19,
        "verseCount": 11
      }
    ],
    "totalVerses": 96,
    "parshaNum": 19
  },
  {
    "name": "Tetzaveh",
    "hebrewName": "תצוה",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 27,
        "startVerse": 20,
        "endChapter": 28,
        "endVerse": 12,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 28,
        "startVerse": 13,
        "endChapter": 28,
        "endVerse": 30,
        "verseCount": 18
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 28,
        "startVerse": 31,
        "endChapter": 28,
        "endVerse": 43,
        "verseCount": 13
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 29,
        "startVerse": 1,
        "endChapter": 29,
        "endVerse": 18,
        "verseCount": 18
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 29,
        "startVerse": 19,
        "endChapter": 29,
        "endVerse": 37,
        "verseCount": 19
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 29,
        "startVerse": 38,
        "endChapter": 29,
        "endVerse": 46,
        "verseCount": 9
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 30,
        "startVerse": 1,
        "endChapter": 30,
        "endVerse": 10,
        "verseCount": 10
      }
    ],
    "totalVerses": 101,
    "parshaNum": 20
  },
  {
    "name": "Ki Tisa",
    "hebrewName": "כי תשא",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 30,
        "startVerse": 11,
        "endChapter": 31,
        "endVerse": 17,
        "verseCount": 45
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 31,
        "startVerse": 18,
        "endChapter": 33,
        "endVerse": 11,
        "verseCount": 47
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 33,
        "startVerse": 12,
        "endChapter": 33,
        "endVerse": 16,
        "verseCount": 5
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 33,
        "startVerse": 17,
        "endChapter": 33,
        "endVerse": 23,
        "verseCount": 7
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 34,
        "startVerse": 1,
        "endChapter": 34,
        "endVerse": 9,
        "verseCount": 9
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 34,
        "startVerse": 10,
        "endChapter": 34,
        "endVerse": 26,
        "verseCount": 17
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 34,
        "startVerse": 27,
        "endChapter": 34,
        "endVerse": 35,
        "verseCount": 9
      }
    ],
    "totalVerses": 139,
    "parshaNum": 21
  },
  {
    "name": "Vayakhel",
    "hebrewName": "ויקהל",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 35,
        "startVerse": 1,
        "endChapter": 35,
        "endVerse": 20,
        "verseCount": 20
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 35,
        "startVerse": 21,
        "endChapter": 35,
        "endVerse": 29,
        "verseCount": 9
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 35,
        "startVerse": 30,
        "endChapter": 36,
        "endVerse": 7,
        "verseCount": 13
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 36,
        "startVerse": 8,
        "endChapter": 36,
        "endVerse": 19,
        "verseCount": 12
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 36,
        "startVerse": 20,
        "endChapter": 37,
        "endVerse": 16,
        "verseCount": 35
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 37,
        "startVerse": 17,
        "endChapter": 37,
        "endVerse": 29,
        "verseCount": 13
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 38,
        "startVerse": 1,
        "endChapter": 38,
        "endVerse": 20,
        "verseCount": 20
      }
    ],
    "totalVerses": 122,
    "parshaNum": 22
  },
  {
    "name": "Vayakhel-Pekudei",
    "hebrewName": "ויקהל־פקודי",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 35,
        "startVerse": 1,
        "endChapter": 35,
        "endVerse": 29,
        "verseCount": 29
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 35,
        "startVerse": 30,
        "endChapter": 37,
        "endVerse": 16,
        "verseCount": 60
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 37,
        "startVerse": 17,
        "endChapter": 37,
        "endVerse": 29,
        "verseCount": 13
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 38,
        "startVerse": 1,
        "endChapter": 39,
        "endVerse": 1,
        "verseCount": 32
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 39,
        "startVerse": 2,
        "endChapter": 39,
        "endVerse": 21,
        "verseCount": 20
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 39,
        "startVerse": 22,
        "endChapter": 39,
        "endVerse": 43,
        "verseCount": 22
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 40,
        "startVerse": 1,
        "endChapter": 40,
        "endVerse": 38,
        "verseCount": 38
      }
    ],
    "totalVerses": 214,
    "parshaNum": 22
  },
  {
    "name": "Pekudei",
    "hebrewName": "פקודי",
    "book": "Exodus",
    "aliyot": [
      {
        "number": 1,
        "book": "Exodus",
        "startChapter": 38,
        "startVerse": 21,
        "endChapter": 39,
        "endVerse": 1,
        "verseCount": 12
      },
      {
        "number": 2,
        "book": "Exodus",
        "startChapter": 39,
        "startVerse": 2,
        "endChapter": 39,
        "endVerse": 21,
        "verseCount": 20
      },
      {
        "number": 3,
        "book": "Exodus",
        "startChapter": 39,
        "startVerse": 22,
        "endChapter": 39,
        "endVerse": 32,
        "verseCount": 11
      },
      {
        "number": 4,
        "book": "Exodus",
        "startChapter": 39,
        "startVerse": 33,
        "endChapter": 39,
        "endVerse": 43,
        "verseCount": 11
      },
      {
        "number": 5,
        "book": "Exodus",
        "startChapter": 40,
        "startVerse": 1,
        "endChapter": 40,
        "endVerse": 16,
        "verseCount": 16
      },
      {
        "number": 6,
        "book": "Exodus",
        "startChapter": 40,
        "startVerse": 17,
        "endChapter": 40,
        "endVerse": 27,
        "verseCount": 11
      },
      {
        "number": 7,
        "book": "Exodus",
        "startChapter": 40,
        "startVerse": 28,
        "endChapter": 40,
        "endVerse": 38,
        "verseCount": 11
      }
    ],
    "totalVerses": 92,
    "parshaNum": 23
  },
  {
    "name": "Vayikra",
    "hebrewName": "ויקרא",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 1,
        "startVerse": 1,
        "endChapter": 1,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 1,
        "startVerse": 14,
        "endChapter": 2,
        "endVerse": 6,
        "verseCount": 10
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 2,
        "startVerse": 7,
        "endChapter": 2,
        "endVerse": 16,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 3,
        "startVerse": 1,
        "endChapter": 3,
        "endVerse": 17,
        "verseCount": 17
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 4,
        "startVerse": 1,
        "endChapter": 4,
        "endVerse": 26,
        "verseCount": 26
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 4,
        "startVerse": 27,
        "endChapter": 5,
        "endVerse": 10,
        "verseCount": 19
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 5,
        "startVerse": 11,
        "endChapter": 5,
        "endVerse": 26,
        "verseCount": 16
      }
    ],
    "totalVerses": 111,
    "parshaNum": 24
  },
  {
    "name": "Tzav",
    "hebrewName": "צו",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 6,
        "startVerse": 1,
        "endChapter": 6,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 6,
        "startVerse": 12,
        "endChapter": 7,
        "endVerse": 10,
        "verseCount": 22
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 7,
        "startVerse": 11,
        "endChapter": 7,
        "endVerse": 38,
        "verseCount": 28
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 8,
        "startVerse": 1,
        "endChapter": 8,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 8,
        "startVerse": 14,
        "endChapter": 8,
        "endVerse": 21,
        "verseCount": 8
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 8,
        "startVerse": 22,
        "endChapter": 8,
        "endVerse": 29,
        "verseCount": 8
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 8,
        "startVerse": 30,
        "endChapter": 8,
        "endVerse": 36,
        "verseCount": 7
      }
    ],
    "totalVerses": 97,
    "parshaNum": 25
  },
  {
    "name": "Shmini",
    "hebrewName": "שמיני",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 9,
        "startVerse": 1,
        "endChapter": 9,
        "endVerse": 16,
        "verseCount": 16
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 9,
        "startVerse": 17,
        "endChapter": 9,
        "endVerse": 23,
        "verseCount": 7
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 9,
        "startVerse": 24,
        "endChapter": 10,
        "endVerse": 11,
        "verseCount": 12
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 10,
        "startVerse": 12,
        "endChapter": 10,
        "endVerse": 15,
        "verseCount": 4
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 10,
        "startVerse": 16,
        "endChapter": 10,
        "endVerse": 20,
        "verseCount": 5
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 11,
        "startVerse": 1,
        "endChapter": 11,
        "endVerse": 32,
        "verseCount": 32
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 11,
        "startVerse": 33,
        "endChapter": 11,
        "endVerse": 47,
        "verseCount": 15
      }
    ],
    "totalVerses": 91,
    "parshaNum": 26
  },
  {
    "name": "Tazria",
    "hebrewName": "תזריע",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 12,
        "startVerse": 1,
        "endChapter": 13,
        "endVerse": 5,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 6,
        "endChapter": 13,
        "endVerse": 17,
        "verseCount": 12
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 18,
        "endChapter": 13,
        "endVerse": 23,
        "verseCount": 6
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 24,
        "endChapter": 13,
        "endVerse": 28,
        "verseCount": 5
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 29,
        "endChapter": 13,
        "endVerse": 39,
        "verseCount": 11
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 40,
        "endChapter": 13,
        "endVerse": 54,
        "verseCount": 15
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 55,
        "endChapter": 13,
        "endVerse": 59,
        "verseCount": 5
      }
    ],
    "totalVerses": 67,
    "parshaNum": 27
  },
  {
    "name": "Tazria-Metzora",
    "hebrewName": "תזריע־מצרע",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 12,
        "startVerse": 1,
        "endChapter": 13,
        "endVerse": 23,
        "verseCount": 31
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 24,
        "endChapter": 13,
        "endVerse": 39,
        "verseCount": 16
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 40,
        "endChapter": 13,
        "endVerse": 54,
        "verseCount": 15
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 13,
        "startVerse": 55,
        "endChapter": 14,
        "endVerse": 20,
        "verseCount": 25
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 21,
        "endChapter": 14,
        "endVerse": 32,
        "verseCount": 12
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 33,
        "endChapter": 15,
        "endVerse": 15,
        "verseCount": 40
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 15,
        "startVerse": 16,
        "endChapter": 15,
        "endVerse": 33,
        "verseCount": 18
      }
    ],
    "totalVerses": 157,
    "parshaNum": 27
  },
  {
    "name": "Metzora",
    "hebrewName": "מצרע",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 1,
        "endChapter": 14,
        "endVerse": 12,
        "verseCount": 12
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 13,
        "endChapter": 14,
        "endVerse": 20,
        "verseCount": 8
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 21,
        "endChapter": 14,
        "endVerse": 32,
        "verseCount": 12
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 33,
        "endChapter": 14,
        "endVerse": 53,
        "verseCount": 21
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 14,
        "startVerse": 54,
        "endChapter": 15,
        "endVerse": 15,
        "verseCount": 19
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 15,
        "startVerse": 16,
        "endChapter": 15,
        "endVerse": 28,
        "verseCount": 13
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 15,
        "startVerse": 29,
        "endChapter": 15,
        "endVerse": 33,
        "verseCount": 5
      }
    ],
    "totalVerses": 90,
    "parshaNum": 28
  },
  {
    "name": "Achrei Mot",
    "hebrewName": "אחרי מות",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 16,
        "startVerse": 1,
        "endChapter": 16,
        "endVerse": 17,
        "verseCount": 17
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 16,
        "startVerse": 18,
        "endChapter": 16,
        "endVerse": 24,
        "verseCount": 7
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 16,
        "startVerse": 25,
        "endChapter": 16,
        "endVerse": 34,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 17,
        "startVerse": 1,
        "endChapter": 17,
        "endVerse": 7,
        "verseCount": 7
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 17,
        "startVerse": 8,
        "endChapter": 18,
        "endVerse": 5,
        "verseCount": 14
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 18,
        "startVerse": 6,
        "endChapter": 18,
        "endVerse": 21,
        "verseCount": 16
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 18,
        "startVerse": 22,
        "endChapter": 18,
        "endVerse": 30,
        "verseCount": 9
      }
    ],
    "totalVerses": 80,
    "parshaNum": 29
  },
  {
    "name": "Achrei Mot-Kedoshim",
    "hebrewName": "אחרי מות־קדשים",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 16,
        "startVerse": 1,
        "endChapter": 16,
        "endVerse": 24,
        "verseCount": 24
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 16,
        "startVerse": 25,
        "endChapter": 17,
        "endVerse": 7,
        "verseCount": 17
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 17,
        "startVerse": 8,
        "endChapter": 18,
        "endVerse": 21,
        "verseCount": 30
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 18,
        "startVerse": 22,
        "endChapter": 19,
        "endVerse": 14,
        "verseCount": 23
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 15,
        "endChapter": 19,
        "endVerse": 32,
        "verseCount": 18
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 33,
        "endChapter": 20,
        "endVerse": 7,
        "verseCount": 12
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 20,
        "startVerse": 8,
        "endChapter": 20,
        "endVerse": 27,
        "verseCount": 20
      }
    ],
    "totalVerses": 144,
    "parshaNum": 29
  },
  {
    "name": "Kedoshim",
    "hebrewName": "קדשים",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 1,
        "endChapter": 19,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 15,
        "endChapter": 19,
        "endVerse": 22,
        "verseCount": 8
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 23,
        "endChapter": 19,
        "endVerse": 32,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 19,
        "startVerse": 33,
        "endChapter": 19,
        "endVerse": 37,
        "verseCount": 5
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 20,
        "startVerse": 1,
        "endChapter": 20,
        "endVerse": 7,
        "verseCount": 7
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 20,
        "startVerse": 8,
        "endChapter": 20,
        "endVerse": 22,
        "verseCount": 15
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 20,
        "startVerse": 23,
        "endChapter": 20,
        "endVerse": 27,
        "verseCount": 5
      }
    ],
    "totalVerses": 64,
    "parshaNum": 30
  },
  {
    "name": "Emor",
    "hebrewName": "אמור",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 21,
        "startVerse": 1,
        "endChapter": 21,
        "endVerse": 15,
        "verseCount": 15
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 21,
        "startVerse": 16,
        "endChapter": 22,
        "endVerse": 16,
        "verseCount": 25
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 22,
        "startVerse": 17,
        "endChapter": 22,
        "endVerse": 33,
        "verseCount": 17
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 23,
        "startVerse": 1,
        "endChapter": 23,
        "endVerse": 22,
        "verseCount": 22
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 23,
        "startVerse": 23,
        "endChapter": 23,
        "endVerse": 32,
        "verseCount": 10
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 23,
        "startVerse": 33,
        "endChapter": 23,
        "endVerse": 44,
        "verseCount": 12
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 24,
        "startVerse": 1,
        "endChapter": 24,
        "endVerse": 23,
        "verseCount": 23
      }
    ],
    "totalVerses": 124,
    "parshaNum": 31
  },
  {
    "name": "Behar",
    "hebrewName": "בהר",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 1,
        "endChapter": 25,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 14,
        "endChapter": 25,
        "endVerse": 18,
        "verseCount": 5
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 19,
        "endChapter": 25,
        "endVerse": 24,
        "verseCount": 6
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 25,
        "endChapter": 25,
        "endVerse": 28,
        "verseCount": 4
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 29,
        "endChapter": 25,
        "endVerse": 38,
        "verseCount": 10
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 39,
        "endChapter": 25,
        "endVerse": 46,
        "verseCount": 8
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 47,
        "endChapter": 26,
        "endVerse": 2,
        "verseCount": 11
      }
    ],
    "totalVerses": 57,
    "parshaNum": 32
  },
  {
    "name": "Behar-Bechukotai",
    "hebrewName": "בהר־בחקתי",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 1,
        "endChapter": 25,
        "endVerse": 18,
        "verseCount": 18
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 19,
        "endChapter": 25,
        "endVerse": 28,
        "verseCount": 10
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 29,
        "endChapter": 25,
        "endVerse": 38,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 25,
        "startVerse": 39,
        "endChapter": 26,
        "endVerse": 9,
        "verseCount": 26
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 26,
        "startVerse": 10,
        "endChapter": 26,
        "endVerse": 46,
        "verseCount": 37
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 1,
        "endChapter": 27,
        "endVerse": 15,
        "verseCount": 15
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 16,
        "endChapter": 27,
        "endVerse": 34,
        "verseCount": 19
      }
    ],
    "totalVerses": 135,
    "parshaNum": 32
  },
  {
    "name": "Bechukotai",
    "hebrewName": "בחקתי",
    "book": "Leviticus",
    "aliyot": [
      {
        "number": 1,
        "book": "Leviticus",
        "startChapter": 26,
        "startVerse": 3,
        "endChapter": 26,
        "endVerse": 5,
        "verseCount": 3
      },
      {
        "number": 2,
        "book": "Leviticus",
        "startChapter": 26,
        "startVerse": 6,
        "endChapter": 26,
        "endVerse": 9,
        "verseCount": 4
      },
      {
        "number": 3,
        "book": "Leviticus",
        "startChapter": 26,
        "startVerse": 10,
        "endChapter": 26,
        "endVerse": 46,
        "verseCount": 37
      },
      {
        "number": 4,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 1,
        "endChapter": 27,
        "endVerse": 15,
        "verseCount": 15
      },
      {
        "number": 5,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 16,
        "endChapter": 27,
        "endVerse": 21,
        "verseCount": 6
      },
      {
        "number": 6,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 22,
        "endChapter": 27,
        "endVerse": 28,
        "verseCount": 7
      },
      {
        "number": 7,
        "book": "Leviticus",
        "startChapter": 27,
        "startVerse": 29,
        "endChapter": 27,
        "endVerse": 34,
        "verseCount": 6
      }
    ],
    "totalVerses": 78,
    "parshaNum": 33
  },
  {
    "name": "Bamidbar",
    "hebrewName": "במדבר",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 1,
        "startVerse": 1,
        "endChapter": 1,
        "endVerse": 19,
        "verseCount": 19
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 1,
        "startVerse": 20,
        "endChapter": 1,
        "endVerse": 54,
        "verseCount": 35
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 2,
        "startVerse": 1,
        "endChapter": 2,
        "endVerse": 34,
        "verseCount": 34
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 3,
        "startVerse": 1,
        "endChapter": 3,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 3,
        "startVerse": 14,
        "endChapter": 3,
        "endVerse": 39,
        "verseCount": 26
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 3,
        "startVerse": 40,
        "endChapter": 3,
        "endVerse": 51,
        "verseCount": 12
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 4,
        "startVerse": 1,
        "endChapter": 4,
        "endVerse": 20,
        "verseCount": 20
      }
    ],
    "totalVerses": 159,
    "parshaNum": 34
  },
  {
    "name": "Nasso",
    "hebrewName": "נשא",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 4,
        "startVerse": 21,
        "endChapter": 4,
        "endVerse": 37,
        "verseCount": 17
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 4,
        "startVerse": 38,
        "endChapter": 4,
        "endVerse": 49,
        "verseCount": 12
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 5,
        "startVerse": 1,
        "endChapter": 5,
        "endVerse": 10,
        "verseCount": 10
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 5,
        "startVerse": 11,
        "endChapter": 6,
        "endVerse": 27,
        "verseCount": 48
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 7,
        "startVerse": 1,
        "endChapter": 7,
        "endVerse": 41,
        "verseCount": 41
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 7,
        "startVerse": 42,
        "endChapter": 7,
        "endVerse": 71,
        "verseCount": 30
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 7,
        "startVerse": 72,
        "endChapter": 7,
        "endVerse": 89,
        "verseCount": 18
      }
    ],
    "totalVerses": 176,
    "parshaNum": 35
  },
  {
    "name": "Beha’alotcha",
    "hebrewName": "בהעלתך",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 8,
        "startVerse": 1,
        "endChapter": 8,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 8,
        "startVerse": 15,
        "endChapter": 8,
        "endVerse": 26,
        "verseCount": 12
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 9,
        "startVerse": 1,
        "endChapter": 9,
        "endVerse": 14,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 9,
        "startVerse": 15,
        "endChapter": 10,
        "endVerse": 10,
        "verseCount": 19
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 10,
        "startVerse": 11,
        "endChapter": 10,
        "endVerse": 34,
        "verseCount": 24
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 10,
        "startVerse": 35,
        "endChapter": 11,
        "endVerse": 29,
        "verseCount": 31
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 11,
        "startVerse": 30,
        "endChapter": 12,
        "endVerse": 16,
        "verseCount": 22
      }
    ],
    "totalVerses": 136,
    "parshaNum": 36
  },
  {
    "name": "Sh’lach",
    "hebrewName": "שלח־לך",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 13,
        "startVerse": 1,
        "endChapter": 13,
        "endVerse": 20,
        "verseCount": 20
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 13,
        "startVerse": 21,
        "endChapter": 14,
        "endVerse": 7,
        "verseCount": 20
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 14,
        "startVerse": 8,
        "endChapter": 14,
        "endVerse": 25,
        "verseCount": 18
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 14,
        "startVerse": 26,
        "endChapter": 15,
        "endVerse": 7,
        "verseCount": 27
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 15,
        "startVerse": 8,
        "endChapter": 15,
        "endVerse": 16,
        "verseCount": 9
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 15,
        "startVerse": 17,
        "endChapter": 15,
        "endVerse": 26,
        "verseCount": 10
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 15,
        "startVerse": 27,
        "endChapter": 15,
        "endVerse": 41,
        "verseCount": 15
      }
    ],
    "totalVerses": 119,
    "parshaNum": 37
  },
  {
    "name": "Korach",
    "hebrewName": "קורח",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 16,
        "startVerse": 1,
        "endChapter": 16,
        "endVerse": 13,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 16,
        "startVerse": 14,
        "endChapter": 16,
        "endVerse": 19,
        "verseCount": 6
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 16,
        "startVerse": 20,
        "endChapter": 17,
        "endVerse": 8,
        "verseCount": 24
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 17,
        "startVerse": 9,
        "endChapter": 17,
        "endVerse": 15,
        "verseCount": 7
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 17,
        "startVerse": 16,
        "endChapter": 17,
        "endVerse": 24,
        "verseCount": 9
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 17,
        "startVerse": 25,
        "endChapter": 18,
        "endVerse": 20,
        "verseCount": 24
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 18,
        "startVerse": 21,
        "endChapter": 18,
        "endVerse": 32,
        "verseCount": 12
      }
    ],
    "totalVerses": 95,
    "parshaNum": 38
  },
  {
    "name": "Chukat",
    "hebrewName": "חוקת",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 19,
        "startVerse": 1,
        "endChapter": 19,
        "endVerse": 17,
        "verseCount": 17
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 19,
        "startVerse": 18,
        "endChapter": 20,
        "endVerse": 6,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 20,
        "startVerse": 7,
        "endChapter": 20,
        "endVerse": 13,
        "verseCount": 7
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 20,
        "startVerse": 14,
        "endChapter": 20,
        "endVerse": 21,
        "verseCount": 8
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 20,
        "startVerse": 22,
        "endChapter": 21,
        "endVerse": 9,
        "verseCount": 17
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 21,
        "startVerse": 10,
        "endChapter": 21,
        "endVerse": 20,
        "verseCount": 11
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 21,
        "startVerse": 21,
        "endChapter": 22,
        "endVerse": 1,
        "verseCount": 16
      }
    ],
    "totalVerses": 87,
    "parshaNum": 39
  },
  {
    "name": "Chukat-Balak",
    "hebrewName": "חוקת־בלק",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 19,
        "startVerse": 1,
        "endChapter": 20,
        "endVerse": 6,
        "verseCount": 28
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 20,
        "startVerse": 7,
        "endChapter": 20,
        "endVerse": 21,
        "verseCount": 15
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 20,
        "startVerse": 22,
        "endChapter": 21,
        "endVerse": 20,
        "verseCount": 28
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 21,
        "startVerse": 21,
        "endChapter": 22,
        "endVerse": 12,
        "verseCount": 27
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 13,
        "endChapter": 22,
        "endVerse": 38,
        "verseCount": 26
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 39,
        "endChapter": 23,
        "endVerse": 26,
        "verseCount": 29
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 23,
        "startVerse": 27,
        "endChapter": 25,
        "endVerse": 9,
        "verseCount": 38
      }
    ],
    "totalVerses": 191,
    "parshaNum": 39
  },
  {
    "name": "Balak",
    "hebrewName": "בלק",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 2,
        "endChapter": 22,
        "endVerse": 12,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 13,
        "endChapter": 22,
        "endVerse": 20,
        "verseCount": 8
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 21,
        "endChapter": 22,
        "endVerse": 38,
        "verseCount": 18
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 22,
        "startVerse": 39,
        "endChapter": 23,
        "endVerse": 12,
        "verseCount": 15
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 23,
        "startVerse": 13,
        "endChapter": 23,
        "endVerse": 26,
        "verseCount": 14
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 23,
        "startVerse": 27,
        "endChapter": 24,
        "endVerse": 13,
        "verseCount": 17
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 24,
        "startVerse": 14,
        "endChapter": 25,
        "endVerse": 9,
        "verseCount": 21
      }
    ],
    "totalVerses": 104,
    "parshaNum": 40
  },
  {
    "name": "Pinchas",
    "hebrewName": "פינחס",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 25,
        "startVerse": 10,
        "endChapter": 26,
        "endVerse": 4,
        "verseCount": 13
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 26,
        "startVerse": 5,
        "endChapter": 26,
        "endVerse": 51,
        "verseCount": 47
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 26,
        "startVerse": 52,
        "endChapter": 27,
        "endVerse": 5,
        "verseCount": 19
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 27,
        "startVerse": 6,
        "endChapter": 27,
        "endVerse": 23,
        "verseCount": 18
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 28,
        "startVerse": 1,
        "endChapter": 28,
        "endVerse": 15,
        "verseCount": 15
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 28,
        "startVerse": 16,
        "endChapter": 29,
        "endVerse": 11,
        "verseCount": 27
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 29,
        "startVerse": 12,
        "endChapter": 30,
        "endVerse": 1,
        "verseCount": 29
      }
    ],
    "totalVerses": 168,
    "parshaNum": 41
  },
  {
    "name": "Matot",
    "hebrewName": "מטות",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 30,
        "startVerse": 2,
        "endChapter": 30,
        "endVerse": 17,
        "verseCount": 16
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 31,
        "startVerse": 1,
        "endChapter": 31,
        "endVerse": 12,
        "verseCount": 12
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 31,
        "startVerse": 13,
        "endChapter": 31,
        "endVerse": 24,
        "verseCount": 12
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 31,
        "startVerse": 25,
        "endChapter": 31,
        "endVerse": 41,
        "verseCount": 17
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 31,
        "startVerse": 42,
        "endChapter": 31,
        "endVerse": 54,
        "verseCount": 13
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 32,
        "startVerse": 1,
        "endChapter": 32,
        "endVerse": 19,
        "verseCount": 19
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 32,
        "startVerse": 20,
        "endChapter": 32,
        "endVerse": 42,
        "verseCount": 23
      }
    ],
    "totalVerses": 112,
    "parshaNum": 42
  },
  {
    "name": "Matot-Masei",
    "hebrewName": "מטות־מסעי",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 30,
        "startVerse": 2,
        "endChapter": 31,
        "endVerse": 12,
        "verseCount": 28
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 31,
        "startVerse": 13,
        "endChapter": 31,
        "endVerse": 54,
        "verseCount": 42
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 32,
        "startVerse": 1,
        "endChapter": 32,
        "endVerse": 19,
        "verseCount": 19
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 32,
        "startVerse": 20,
        "endChapter": 33,
        "endVerse": 49,
        "verseCount": 72
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 33,
        "startVerse": 50,
        "endChapter": 34,
        "endVerse": 15,
        "verseCount": 22
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 34,
        "startVerse": 16,
        "endChapter": 35,
        "endVerse": 8,
        "verseCount": 22
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 35,
        "startVerse": 9,
        "endChapter": 36,
        "endVerse": 13,
        "verseCount": 39
      }
    ],
    "totalVerses": 244,
    "parshaNum": 42
  },
  {
    "name": "Masei",
    "hebrewName": "מסעי",
    "book": "Numbers",
    "aliyot": [
      {
        "number": 1,
        "book": "Numbers",
        "startChapter": 33,
        "startVerse": 1,
        "endChapter": 33,
        "endVerse": 10,
        "verseCount": 10
      },
      {
        "number": 2,
        "book": "Numbers",
        "startChapter": 33,
        "startVerse": 11,
        "endChapter": 33,
        "endVerse": 49,
        "verseCount": 39
      },
      {
        "number": 3,
        "book": "Numbers",
        "startChapter": 33,
        "startVerse": 50,
        "endChapter": 34,
        "endVerse": 15,
        "verseCount": 22
      },
      {
        "number": 4,
        "book": "Numbers",
        "startChapter": 34,
        "startVerse": 16,
        "endChapter": 34,
        "endVerse": 29,
        "verseCount": 14
      },
      {
        "number": 5,
        "book": "Numbers",
        "startChapter": 35,
        "startVerse": 1,
        "endChapter": 35,
        "endVerse": 8,
        "verseCount": 8
      },
      {
        "number": 6,
        "book": "Numbers",
        "startChapter": 35,
        "startVerse": 9,
        "endChapter": 35,
        "endVerse": 34,
        "verseCount": 26
      },
      {
        "number": 7,
        "book": "Numbers",
        "startChapter": 36,
        "startVerse": 1,
        "endChapter": 36,
        "endVerse": 13,
        "verseCount": 13
      }
    ],
    "totalVerses": 132,
    "parshaNum": 43
  },
  {
    "name": "Devarim",
    "hebrewName": "דברים",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 1,
        "startVerse": 1,
        "endChapter": 1,
        "endVerse": 10,
        "verseCount": 10
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 1,
        "startVerse": 11,
        "endChapter": 1,
        "endVerse": 21,
        "verseCount": 11
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 1,
        "startVerse": 22,
        "endChapter": 1,
        "endVerse": 38,
        "verseCount": 17
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 1,
        "startVerse": 39,
        "endChapter": 2,
        "endVerse": 1,
        "verseCount": 9
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 2,
        "startVerse": 2,
        "endChapter": 2,
        "endVerse": 30,
        "verseCount": 29
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 2,
        "startVerse": 31,
        "endChapter": 3,
        "endVerse": 14,
        "verseCount": 21
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 3,
        "startVerse": 15,
        "endChapter": 3,
        "endVerse": 22,
        "verseCount": 8
      }
    ],
    "totalVerses": 105,
    "parshaNum": 44
  },
  {
    "name": "Vaetchanan",
    "hebrewName": "ואתחנן",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 3,
        "startVerse": 23,
        "endChapter": 4,
        "endVerse": 4,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 4,
        "startVerse": 5,
        "endChapter": 4,
        "endVerse": 40,
        "verseCount": 36
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 4,
        "startVerse": 41,
        "endChapter": 4,
        "endVerse": 49,
        "verseCount": 9
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 5,
        "startVerse": 1,
        "endChapter": 5,
        "endVerse": 18,
        "verseCount": 18
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 5,
        "startVerse": 19,
        "endChapter": 6,
        "endVerse": 3,
        "verseCount": 15
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 6,
        "startVerse": 4,
        "endChapter": 6,
        "endVerse": 25,
        "verseCount": 22
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 7,
        "startVerse": 1,
        "endChapter": 7,
        "endVerse": 11,
        "verseCount": 11
      }
    ],
    "totalVerses": 122,
    "parshaNum": 45
  },
  {
    "name": "Eikev",
    "hebrewName": "עקב",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 7,
        "startVerse": 12,
        "endChapter": 8,
        "endVerse": 10,
        "verseCount": 25
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 8,
        "startVerse": 11,
        "endChapter": 9,
        "endVerse": 3,
        "verseCount": 13
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 9,
        "startVerse": 4,
        "endChapter": 9,
        "endVerse": 29,
        "verseCount": 26
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 10,
        "startVerse": 1,
        "endChapter": 10,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 10,
        "startVerse": 12,
        "endChapter": 11,
        "endVerse": 9,
        "verseCount": 20
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 11,
        "startVerse": 10,
        "endChapter": 11,
        "endVerse": 21,
        "verseCount": 12
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 11,
        "startVerse": 22,
        "endChapter": 11,
        "endVerse": 25,
        "verseCount": 4
      }
    ],
    "totalVerses": 111,
    "parshaNum": 46
  },
  {
    "name": "Re’eh",
    "hebrewName": "ראה",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 11,
        "startVerse": 26,
        "endChapter": 12,
        "endVerse": 10,
        "verseCount": 17
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 12,
        "startVerse": 11,
        "endChapter": 12,
        "endVerse": 28,
        "verseCount": 18
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 12,
        "startVerse": 29,
        "endChapter": 13,
        "endVerse": 19,
        "verseCount": 22
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 14,
        "startVerse": 1,
        "endChapter": 14,
        "endVerse": 21,
        "verseCount": 21
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 14,
        "startVerse": 22,
        "endChapter": 14,
        "endVerse": 29,
        "verseCount": 8
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 15,
        "startVerse": 1,
        "endChapter": 15,
        "endVerse": 18,
        "verseCount": 18
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 15,
        "startVerse": 19,
        "endChapter": 16,
        "endVerse": 17,
        "verseCount": 22
      }
    ],
    "totalVerses": 126,
    "parshaNum": 47
  },
  {
    "name": "Shoftim",
    "hebrewName": "שופטים",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 16,
        "startVerse": 18,
        "endChapter": 17,
        "endVerse": 13,
        "verseCount": 18
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 17,
        "startVerse": 14,
        "endChapter": 17,
        "endVerse": 20,
        "verseCount": 7
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 18,
        "startVerse": 1,
        "endChapter": 18,
        "endVerse": 5,
        "verseCount": 5
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 18,
        "startVerse": 6,
        "endChapter": 18,
        "endVerse": 13,
        "verseCount": 8
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 18,
        "startVerse": 14,
        "endChapter": 19,
        "endVerse": 13,
        "verseCount": 22
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 19,
        "startVerse": 14,
        "endChapter": 20,
        "endVerse": 9,
        "verseCount": 17
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 20,
        "startVerse": 10,
        "endChapter": 21,
        "endVerse": 9,
        "verseCount": 20
      }
    ],
    "totalVerses": 97,
    "parshaNum": 48
  },
  {
    "name": "Ki Teitzei",
    "hebrewName": "כי־תצא",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 21,
        "startVerse": 10,
        "endChapter": 21,
        "endVerse": 21,
        "verseCount": 12
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 21,
        "startVerse": 22,
        "endChapter": 22,
        "endVerse": 7,
        "verseCount": 9
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 22,
        "startVerse": 8,
        "endChapter": 23,
        "endVerse": 7,
        "verseCount": 29
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 23,
        "startVerse": 8,
        "endChapter": 23,
        "endVerse": 24,
        "verseCount": 17
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 23,
        "startVerse": 25,
        "endChapter": 24,
        "endVerse": 4,
        "verseCount": 6
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 24,
        "startVerse": 5,
        "endChapter": 24,
        "endVerse": 13,
        "verseCount": 9
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 24,
        "startVerse": 14,
        "endChapter": 25,
        "endVerse": 19,
        "verseCount": 28
      }
    ],
    "totalVerses": 110,
    "parshaNum": 49
  },
  {
    "name": "Ki Tavo",
    "hebrewName": "כי־תבוא",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 26,
        "startVerse": 1,
        "endChapter": 26,
        "endVerse": 11,
        "verseCount": 11
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 26,
        "startVerse": 12,
        "endChapter": 26,
        "endVerse": 15,
        "verseCount": 4
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 26,
        "startVerse": 16,
        "endChapter": 26,
        "endVerse": 19,
        "verseCount": 4
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 27,
        "startVerse": 1,
        "endChapter": 27,
        "endVerse": 10,
        "verseCount": 10
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 27,
        "startVerse": 11,
        "endChapter": 28,
        "endVerse": 6,
        "verseCount": 22
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 28,
        "startVerse": 7,
        "endChapter": 28,
        "endVerse": 69,
        "verseCount": 63
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 29,
        "startVerse": 1,
        "endChapter": 29,
        "endVerse": 8,
        "verseCount": 8
      }
    ],
    "totalVerses": 122,
    "parshaNum": 50
  },
  {
    "name": "Nitzavim",
    "hebrewName": "נצבים",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 29,
        "startVerse": 9,
        "endChapter": 29,
        "endVerse": 11,
        "verseCount": 3
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 29,
        "startVerse": 12,
        "endChapter": 29,
        "endVerse": 14,
        "verseCount": 3
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 29,
        "startVerse": 15,
        "endChapter": 29,
        "endVerse": 28,
        "verseCount": 14
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 1,
        "endChapter": 30,
        "endVerse": 6,
        "verseCount": 6
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 7,
        "endChapter": 30,
        "endVerse": 10,
        "verseCount": 4
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 11,
        "endChapter": 30,
        "endVerse": 14,
        "verseCount": 4
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 15,
        "endChapter": 30,
        "endVerse": 20,
        "verseCount": 6
      }
    ],
    "totalVerses": 40,
    "parshaNum": 51
  },
  {
    "name": "Nitzavim-Vayeilech",
    "hebrewName": "נצבים־וילך",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 29,
        "startVerse": 9,
        "endChapter": 29,
        "endVerse": 28,
        "verseCount": 20
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 1,
        "endChapter": 30,
        "endVerse": 6,
        "verseCount": 6
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 7,
        "endChapter": 30,
        "endVerse": 14,
        "verseCount": 8
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 30,
        "startVerse": 15,
        "endChapter": 31,
        "endVerse": 6,
        "verseCount": 12
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 7,
        "endChapter": 31,
        "endVerse": 13,
        "verseCount": 7
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 14,
        "endChapter": 31,
        "endVerse": 19,
        "verseCount": 6
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 20,
        "endChapter": 31,
        "endVerse": 30,
        "verseCount": 11
      }
    ],
    "totalVerses": 70,
    "parshaNum": 51
  },
  {
    "name": "Vayeilech",
    "hebrewName": "וילך",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 1,
        "endChapter": 31,
        "endVerse": 3,
        "verseCount": 3
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 4,
        "endChapter": 31,
        "endVerse": 6,
        "verseCount": 3
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 7,
        "endChapter": 31,
        "endVerse": 9,
        "verseCount": 3
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 10,
        "endChapter": 31,
        "endVerse": 13,
        "verseCount": 4
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 14,
        "endChapter": 31,
        "endVerse": 19,
        "verseCount": 6
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 20,
        "endChapter": 31,
        "endVerse": 24,
        "verseCount": 5
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 31,
        "startVerse": 25,
        "endChapter": 31,
        "endVerse": 30,
        "verseCount": 6
      }
    ],
    "totalVerses": 30,
    "parshaNum": 52
  },
  {
    "name": "Ha’azinu",
    "hebrewName": "האזינו",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 1,
        "endChapter": 32,
        "endVerse": 6,
        "verseCount": 6
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 7,
        "endChapter": 32,
        "endVerse": 12,
        "verseCount": 6
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 13,
        "endChapter": 32,
        "endVerse": 18,
        "verseCount": 6
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 19,
        "endChapter": 32,
        "endVerse": 28,
        "verseCount": 10
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 29,
        "endChapter": 32,
        "endVerse": 39,
        "verseCount": 11
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 40,
        "endChapter": 32,
        "endVerse": 43,
        "verseCount": 4
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 32,
        "startVerse": 44,
        "endChapter": 32,
        "endVerse": 52,
        "verseCount": 9
      }
    ],
    "totalVerses": 52,
    "parshaNum": 53
  },
  {
    "name": "Vezot Haberakhah",
    "hebrewName": "וזאת הברכה",
    "book": "Deuteronomy",
    "aliyot": [
      {
        "number": 1,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 1,
        "endChapter": 33,
        "endVerse": 7,
        "verseCount": 7
      },
      {
        "number": 2,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 8,
        "endChapter": 33,
        "endVerse": 12,
        "verseCount": 5
      },
      {
        "number": 3,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 13,
        "endChapter": 33,
        "endVerse": 17,
        "verseCount": 5
      },
      {
        "number": 4,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 18,
        "endChapter": 33,
        "endVerse": 21,
        "verseCount": 4
      },
      {
        "number": 5,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 22,
        "endChapter": 33,
        "endVerse": 26,
        "verseCount": 5
      },
      {
        "number": 6,
        "book": "Deuteronomy",
        "startChapter": 33,
        "startVerse": 27,
        "endChapter": 33,
        "endVerse": 29,
        "verseCount": 3
      },
      {
        "number": 7,
        "book": "Deuteronomy",
        "startChapter": 34,
        "startVerse": 1,
        "endChapter": 34,
        "endVerse": 12,
        "verseCount": 12
      }
    ],
    "totalVerses": 41,
    "parshaNum": 54
  }
];
